### PR TITLE
Add articles form 

### LINKED ISSUE #27: Add articles form to create articles
The form should contain:
- creator field with a dropdown (we will have a pressed of creators)
...the rest of the article fields that are needed

### PR DESCRIPTION
**Pull request by archanaserver**
Add articles form, to create an article | based on:  a7254c3e528c096dc3fb03c46e9d578523dd2dbd

This PR contains the following:
- a new form component file: /../components/ArticlesForm.js
-  used patternfly to add form fields i.e. article title and description
- css is not yet added in this.

Resolves #27 Add articles form to create articles

### CODE REVIEW

**Comment by archanaserver** [comment]
@Ron-Lavi here the[ eslint checks ](https://github.com/girijaasoni/newsletterApplicaton/actions/runs/3827195723/jobs/6511574967) are failing, which is coming from girija's pr. How can we fix this?

**Comment by Ron-Lavi** [comment]
Probably the eslint issue will be resolved in @girijaasoni PR and then you will need to rebase it,
@girijaasoni can you review this PR?

**Comment by Ron-Lavi** [comment]
Hey @girijaasoni can you revert this merge? I haven't reviewed it yet :)

**Comment by girijaasoni** [comment]
@Ron Lavi ***@***.***> I was working with git reset and The code got
messed up
I was trying to push a commit to my branch and it got pushed to the main
branch and then i tried to reset the commit, it deleted the pull
request and made a git mess

**Comment by Ron-Lavi** [comment]
No problem, in such cases `git reflog` might be your best friend :)

**Pull request merged**
